### ISSUE TITLE
Error: Cannot find module 'vue-eslint-parser'

### ISSUE THREAD

**Issue by hakula139** [idahogurl/vs-code-prettier-eslint#118]
**Describe the bug**

When formatting a `.vue` file with this extension, an error occurred:

```text
Error: Cannot find module 'vue-eslint-parser'
Require stack:
- /Users/hakula/.vscode/extensions/rvest.vs-code-prettier-eslint-5.0.4/dist/extension.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:987:15)
    at Function.p.resolve (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:761)
    at Lge (/Users/hakula/.vscode/extensions/rvest.vs-code-prettier-eslint-5.0.4/dist/extension.js:180:1337)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

While if I use `prettier-eslint-cli` to format a `.vue` file, everything works fine:

```bash
$ prettier-eslint ./src/App.vue
```

Output:

```text
<template>
  <router-view />
</template>
1 file was unchanged
```

The module `vue-eslint-parser` is indeed installed locally with the project, with version 9.1.0. And I've also tried to install it globally, but to no avail. Both the extension and the CLI were at the latest version.

**To Reproduce**

1. Clone the [repository] and build with Yarn 3.3.0.
2. Go to `src/App.vue`.
3. Format document with extension `prettier-eslint`.
4. See error in the Output panel.

[repository]: https://github.com/hakula139/vue-ts-app-template

**Expected behavior**

No error occurred when formatting, and the file is then properly formatted.

**Example Project**

Please check this [repository].

It might not be a minimal example, but making `prettier` and `ESLint` work together seems to be really complicated and requires many extra dependencies and plugins. This is a "simple" template I've tried very hard to make everything works, but since I've tried to upgrade the dependencies recently, it suddenly breaks down. Reverting everything back to an older version is not an expected option, because the last working version was created about a year ago, and I do hope to upgrade many of the dependencies for security reasons and new features. Yet reverting some of them which breaks this extension is certainly acceptable, but I've tried hours failing to find them out, so please forgive me for leaving them as is.

**Versions (please complete the following information):**

- VS Code Prettier ESLint extension: 5.0.4
- Visual Studio Code: 1.73.1
- Node: 16.17.0
- Package Manager: yarn 3.3.0
- prettier: 2.8.0
- eslint: 8.28.0

**System Specifications (please complete the following information):**

- OS: macOS Monterey 12.6
- Processor: Apple Silicon M1 Pro
- RAM Size: 32 GB

Any further information could be provided if required. Thanks for your great extension!

**Comment by idahogurl** [comment]
@hakula139 I cannot reproduce the issue. Have you tried deleting your `node_modules` folder and running `yarn` again?

**Comment by hakula139** [comment]
> @hakula139 I cannot reproduce the issue. Have you tried deleting your `node_modules` folder and running `yarn` again?

Wow, that works 😂. Can't believe it's that easy. Thanks for your assistance!
